
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dejjamumxdoctwxyrxij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlamphbXVteGRvY3R3eHlyeGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDM3NzYsImV4cCI6MjA1NzQ3OTc3Nn0.MynpCPHVAFcRF-ZbS3LnKd06uOLJe2e7nlkbLJlrTxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'f1-tournament-auth-token',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'X-Client-Info': 'f1-tournament-app',
    },
  },
  // Enable the functions module to call Edge Functions
  functions: {
    // Not needed if using the default URL
  },
});
